/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   cleanup.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: bkiskac <bkiskac@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/05/16 21:31:28 by bkiskac           #+#    #+#             */
/*   Updated: 2025/07/08 15:22:09 by bkiskac          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

/**
 * @brief Frees all resources used during a single iteration of the command loop.
 *
 * This function is crucial for preventing memory leaks by ensuring that all
 * dynamically allocated memory for a single command line is released after it
 * has been processed. It is called at the end of each iteration, both on
 * successful execution and in case of a parsing or execution error.
 *
 * The function performs the following cleanup tasks:
 * - `clear_command_list`: Frees the linked list of `t_command` structures,
 *   including all associated arguments and redirection information.
 * - `clear_token_list`: Frees the linked list of `t_token` structures that was
 *   generated by the lexer.
 * - It also frees the `raw_line_ptr`, which is the original string read from
 *   the user.
 *
 * @param raw_line_ptr A pointer to the raw input string read from `readline`.
 *                     This pointer is freed by the function.
 * @param shell A pointer to the `t_shell` structure, which holds the pointers
 *              to the command and token lists that need to be cleared.
 */
void	cleanup_iteration_resources(char *raw_line_ptr, t_shell *shell)
{
	if (!shell)
		return ;
	if (shell->command)
	{
		clear_command_list(shell->command);
		shell->command = NULL;
	}
	if (shell->tokens)
	{
		clear_token_list(&shell->tokens);
		shell->tokens = NULL;
	}
	if (raw_line_ptr)
		free(raw_line_ptr);
}

/**
 * @brief Frees memory allocated specifically within a child process
 * before exiting.
 *
 * This function should be called from a forked process before it exits,
 * especially on an error path (e.g., command not found).
 * It frees resources that are not managed by the main process, such as
 * the command table, token list, and the duplicated environment array
 * for execve.
 *
 * @param shell A pointer to the main shell data structure.
 * @param env_array The environment array created for execve, if any.
 */
void	cleanup_child_process(t_shell *shell, char **env_array)
{
	if (env_array)
		ft_free_all(env_array);
	if (shell && shell->command)
	{
		clear_command_list(shell->command);
		shell->command = NULL;
	}
	if (shell && shell->tokens)
	{
		clear_token_list(&shell->tokens);
		shell->tokens = NULL;
	}
	if (shell && shell->line)
	{
		free(shell->line);
		shell->line = NULL;
	}
	if (shell && shell->env)
	{
		free_env(shell->env);
		shell->env = NULL;
	}
}

/**
 * @brief Cleans up heredoc structure and frees memory.
 *
 * This function frees all memory associated with the heredoc
 * structure and resets the pointer to NULL.
 *
 * @param shell The shell structure containing heredoc to cleanup.
 */
void	cleanup_heredoc(t_shell *shell)
{
	if (!shell->heredoc)
		return ;
	if (shell->heredoc->lines)
		free_heredoc(shell->heredoc->lines, shell->heredoc->count);
	if (shell->heredoc->pipe_fd != -1)
		close(shell->heredoc->pipe_fd);
	free(shell->heredoc);
	shell->heredoc = NULL;
}

/**
 * @brief Cleans up memory allocated for cd command operations.
 *
 * This utility function frees the memory allocated for old_pwd, new_pwd,
 * and target directory paths. Handles NULL pointers safely.
 *
 * @param old_pwd The old working directory path to free.
 * @param new_pwd The new working directory path to free.
 * @param target The target directory path to free.
 * @param return_value The value to return after cleanup.
 * @return The provided return_value parameter.
 */
int	cleanup_cd_memory(char *old_pwd, char *new_pwd, char *target,
	int return_value)
{
	if (old_pwd)
		free(old_pwd);
	if (new_pwd)
		free(new_pwd);
	if (target)
		free(target);
	return (return_value);
}
